version: '3'

services:

    node:
        build:
            context: ./node
            dockerfile: Dockerfile
        container_name: node
        entrypoint: dockerize -wait tcp://db:3306 -timeout 30s node server.js
        networks:
            - nodenet
        volumes: 
            - ./node:/usr/src/app
            - /usr/src/app/node_modules
        tty: true

        
    nginx:
        build:
            context: ./nginx
            dockerfile: Dockerfile
        container_name: nginx
        networks:
            - nodenet
        ports: 
            - "8080:80"

    db:
        image: mysql:5.7
        command: --innodb-use-native-aio=0
        container_name: db
        restart: always
        tty: true
        volumes: 
            - ./mysql:/var/lib/mysql
        environment: 
            - MYSQL_DATABASE=nodedb
            - MYSQL_ROOT_PASSWORD=root
        networks: 
            - nodenet
        
networks: 
    nodenet:
        driver: bridge